import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const targetPath = join(__dirname, '../src/env.config.ts');

const apiUrl = process.env.API_URL ?? 'http://localhost:8081';
const cloudinaryCloudName = process.env.CLOUDINARY_CLOUD_NAME ?? 'oceanmind';
const cloudinaryUploadPreset = process.env.CLOUDINARY_UPLOAD_PRESET ?? 'react_upload';

const content = `// Generated by scripts/generate-env.mjs — do not edit manually
export const API_URL = '${apiUrl}';
export const CLOUDINARY_CLOUD_NAME = '${cloudinaryCloudName}';
export const CLOUDINARY_UPLOAD_PRESET = '${cloudinaryUploadPreset}';
`;

writeFileSync(targetPath, content, 'utf8');
console.log(`Generated env config with API_URL=${apiUrl}`);
