// Generated by scripts/generate-env.mjs — do not edit manually
export const API_URL = 'http://localhost:8081';
export const CLOUDINARY_CLOUD_NAME = 'oceanmind';
export const CLOUDINARY_UPLOAD_PRESET = 'react_upload';
