spring.datasource.url=jdbc:mysql://localhost:3306/htms?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=039402
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
